### ISSUE TITLE
Fix autodoc problems

### ISSUE THREAD

**Issue by cpanuski** [QPG-MIT/slmsuite#14]
Side navigation tree doesn't expand to show all pages unless that page is visited via links from main panel.

**Comment by ichristen** [comment]
Problem looks inherent to Sphinx based on browsing other readthedocs pages. Consider submitting issue to Sphinx.

**Comment by ichristen** [comment]
Yo, bulleted lists are broken too. e.g. https://slmsuite.readthedocs.io/en/latest/why.html

**Comment by ichristen** [comment]
Reclosing as this Sphinx issue is fixed.
