### ISSUE TITLE
`self.phase_ff` in `WGS-Kim` + `stats_group=["computational_spot"]`

### ISSUE THREAD

**Issue by LeoKonzett** [QPG-MIT/slmsuite#34]
Hey, 

### WGS Kim

When using `method="WGS-Kim"`, we have the following code snippet:
```
# line 658 in slmsuite.holography.algorithms
if (
         "fixed_phase" in self.flags
          and self.flags["fixed_phase"]
          and self.phase_ff is not None
):
```

I wonder about `self.phase_ff`: If I initialize a `SpotHologram` class via e.g. `make_rectangular_array()`, we have `.phase_ff = None`.
If I then run `.optimize`, `self.phase_ff` only gets set at the end of the loop. 

Put didfferently, the code snippet I posted above always evaluates to `False` because `self.phase_ff = None`. Hence, the far-field phase gets never fixed and I essentially run `WGS-Leonardo`

Surely I am missing something or doing something wrong as `WGS-Kim` seems to work fine in the example docs.

### `stats_groups=["computational_spot"]`

I feel that the efficiency when using the above stat group is not calculated properly for high-resolution images.
What happens is that we compare the the total power in an image `total = np.sum(ns.square(self.amplitude_ff))`
with the power in *single* pixels, e.g. `self.amplitude_ff[self.spot_knm_rounded[:, 0], self.spot_knm_rounded[:, 1]`.

My fix is
```
# In meth: SpotHologram._calculate_stats_spots():

  if "computational_spot" in stat_groups:
            total = cp.sum(cp.square(self.amp_ff))

            psf_knm = 2 * int(toolbox.smallest_distance(self.spot_knm_rounded) / 2) + 1
            if psf_knm < 10:
                logging.warning("In meth: _calculate_stats_spots: ROI around simulated spots is clipped to 10.")
                psf_knm = 10
            if psf_knm > 50:
                logging.warning("In meth: _calculate_stats_spots: ROI around simulated spots is clipped to 50")
                psf_knm = 50

            feedback = analysis.take(
                np.square(self.amp_ff), self.spot_knm_rounded, psf_knm, centered=True, integrate=True
            )
            feedback = np.sqrt(np.array(feedback, dtype=self.dtype))

            stats["computational_spot"] = self._calculate_stats(
                feedback,
                self.spot_amp,
                efficiency_compensation=False,
                total=total,
            )
```
This surely is slower but will calculate the efficiency properly.
Similarly, one can update the feedback for `SpotHologram` classes, e.g. via
```
# in meth: SpotHologram._update_weights():

        elif feedback == "computational_spot":
            psf_knm = 2 * int(toolbox.smallest_distance(self.spot_knm_rounded) / 2) + 1
            if psf_knm < 10:
                logging.warning("In meth: _calculate_stats_spots: ROI around simulated spots is clipped to 10.")
                psf_knm = 10
            if psf_knm > 50:
                logging.warning("In meth: _calculate_stats_spots: ROI around simulated spots is clipped to 50")
                psf_knm = 50

            logging.info("Use updated routine to calculate weights for Spot Holograms")
            feedback = analysis.take(
                np.square(self.amp_ff), self.spot_knm_rounded, psf_knm, centered=True, integrate=True
            )
            feedback = np.sqrt(np.array(feedback, dtype=self.dtype))
            spot_amp_norm = self.spot_amp * 1 / Hologram._norm(self.spot_amp)

            self.weights[self.spot_knm_rounded[1, :], self.spot_knm_rounded[0, :]] = (
                self._update_weights_generic(
                    self.weights[self.spot_knm_rounded[1, :], self.spot_knm_rounded[0, :]],
                    cp.array(feedback),
                    spot_amp_norm,
                )
            )
```
Thanks for looking into this!

**Comment by ichristen** [comment]
Hi Leo,

Sorry for my very late reply. I think I was at March Meeting when you sent this out, and then I got mixed up with which issues I replied to. Please feel free to poke in the future.

I think all of what you mentioned was already fixed in the dev branch when you noted the problem. dev has now been pulled into main (#35). I would suggest moving to the updated code if possible. Let us know if you see similar issues!
