### ISSUE TITLE
Wavefront calibration link

### ISSUE THREAD

**Issue by lufermar** [QPG-MIT/slmsuite#47]
Hi,
this is not a code issue but I think it's good to solve it: in the documentation of `wavefront_calibrate` there is a link in _This procedure involves [iteratively interfering light diffracted from superpixels across an SLM with a reference superpixe](https://doi.org/10.1038/nphoton.2010.8)_ . 
I am not convinced that this is the intended link. 
Best,
L.

**Comment by ichristen** [comment]
Hi @lufermar ,

Thanks for finding this! It looks like I missed a 5 in the url.

https://www.nature.com/articles/nphoton.2010.8
->
https://www.nature.com/articles/nphoton.2010.85

Please see this fixed in `e83277b`.

Best,
Ian
